/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steppermclient;

/**
 *
 * @author snide
 */
public class ClientFrame extends javax.swing.JFrame {

    private String Username = null;
    private Thread cThread = null;
    private Client client = null;
    
    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        initComponents();
        Initialize();
    }
    
    private void Initialize()
    {
        write("Hello Chris");
        Username = UsernameTextField.getText();
        client = new Client(this, Username);
        cThread = new Thread(client);
        cThread.start();       
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directionsGroup = new javax.swing.ButtonGroup();
        stepsGroup = new javax.swing.ButtonGroup();
        revsGroup = new javax.swing.ButtonGroup();
        UsernameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MainTextWin = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        CWButton = new javax.swing.JRadioButton();
        CCWButton = new javax.swing.JRadioButton();
        StartButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        CWButton1 = new javax.swing.JRadioButton();
        CWButton2 = new javax.swing.JRadioButton();
        DegreesTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CWButton3 = new javax.swing.JRadioButton();
        CWButton4 = new javax.swing.JRadioButton();
        DelaySlider = new javax.swing.JSlider();
        DelayTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        VScanButton = new javax.swing.JButton();
        HScanButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        UsernameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        UsernameTextField.setText("Chris");
        UsernameTextField.setToolTipText("");

        MainTextWin.setColumns(20);
        MainTextWin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MainTextWin.setForeground(new java.awt.Color(0, 0, 255));
        MainTextWin.setRows(5);
        jScrollPane1.setViewportView(MainTextWin);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Rotation:");
        jLabel1.setToolTipText("");

        LoginButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setToolTipText("");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        directionsGroup.add(CWButton);
        CWButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CWButton.setSelected(true);
        CWButton.setText("Clockwise");
        CWButton.setToolTipText("");
        CWButton.setActionCommand("cw");

        directionsGroup.add(CCWButton);
        CCWButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CCWButton.setText("Counter Clockwise");
        CCWButton.setToolTipText("");
        CCWButton.setActionCommand("ccw");

        StartButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        StopButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        QuitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        QuitButton.setText("Quit");
        QuitButton.setToolTipText("");
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        stepsGroup.add(CWButton1);
        CWButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CWButton1.setText("Half Step");
        CWButton1.setToolTipText("");
        CWButton1.setActionCommand("half");

        revsGroup.add(CWButton2);
        CWButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CWButton2.setText("Continuous");
        CWButton2.setActionCommand("cont");

        DegreesTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DegreesTextField.setText("180");
        DegreesTextField.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("(degrees)");
        jLabel3.setToolTipText("");

        revsGroup.add(CWButton3);
        CWButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CWButton3.setSelected(true);
        CWButton3.setText("Non-continuous");
        CWButton3.setActionCommand("noncont");

        stepsGroup.add(CWButton4);
        CWButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CWButton4.setSelected(true);
        CWButton4.setText("Full Step");
        CWButton4.setActionCommand("full");

        DelaySlider.setMajorTickSpacing(10);
        DelaySlider.setMinimum(2);
        DelaySlider.setMinorTickSpacing(2);
        DelaySlider.setToolTipText("");
        DelaySlider.setValue(2);
        DelaySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DelaySliderStateChanged(evt);
            }
        });
        DelaySlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DelaySliderMouseReleased(evt);
            }
        });

        DelayTextField.setEditable(false);
        DelayTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DelayTextField.setText("2");
        DelayTextField.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("msec");
        jLabel4.setToolTipText("");

        VScanButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        VScanButton.setText("Scan V");

        HScanButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        HScanButton1.setText("Scan H");
        HScanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HScanButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CWButton2)
                                    .addComponent(CWButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CWButton1)
                                    .addComponent(CWButton4))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CCWButton)
                                    .addComponent(CWButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(HScanButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(DelaySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DelayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LoginButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(VScanButton)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(QuitButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DegreesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CWButton)
                            .addComponent(StartButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CWButton4)
                            .addComponent(CWButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCWButton)
                    .addComponent(StopButton)
                    .addComponent(CWButton1)
                    .addComponent(CWButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DegreesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginButton)
                            .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(DelayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(HScanButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VScanButton)
                        .addGap(18, 18, 18)
                        .addComponent(DelaySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        client.SendTextMessage("username," + UsernameTextField.getText() + ",");
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        write("terminating connection to server...");
        client.SendTextMessage("terminate,");
        client.CloseClient();
        cThread.interrupt();
        System.exit(0);
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        client.SendTextMessage("terminate,");
        client.CloseClient();
        cThread.interrupt();
    }//GEN-LAST:event_formWindowClosing

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        String direction = directionsGroup.getSelection().getActionCommand();
        
        String steptype = stepsGroup.getSelection().getActionCommand();
        String revolutions = revsGroup.getSelection().getActionCommand();
        String message = "motordata," + direction + "," 
                + DegreesTextField.getText() + "," + steptype + ","
                + revolutions + ","
                + DelayTextField.getText() + ",";         
        client.SendTextMessage(message);
    }//GEN-LAST:event_StartButtonActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        client.SendTextMessage("stop,");
    }//GEN-LAST:event_StopButtonActionPerformed

    private void DelaySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DelaySliderStateChanged
        int value = DelaySlider.getValue();
        DelayTextField.setText(Integer.toString(value));
    }//GEN-LAST:event_DelaySliderStateChanged

    private void DelaySliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelaySliderMouseReleased
        client.SendTextMessage("delay," 
                + Integer.toString(DelaySlider.getValue()) + ",");
    }//GEN-LAST:event_DelaySliderMouseReleased

    private void HScanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HScanButton1ActionPerformed
        String message = "scan," + DegreesTextField.getText() + ",0," 
                + DelayTextField.getText() + ",";     
        
        client.SendTextMessage(message);
    }//GEN-LAST:event_HScanButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }
    
    public void write(String input)
    {
        MainTextWin.append( input + "\n");
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CCWButton;
    private javax.swing.JRadioButton CWButton;
    private javax.swing.JRadioButton CWButton1;
    private javax.swing.JRadioButton CWButton2;
    private javax.swing.JRadioButton CWButton3;
    private javax.swing.JRadioButton CWButton4;
    private javax.swing.JTextField DegreesTextField;
    private javax.swing.JSlider DelaySlider;
    private javax.swing.JTextField DelayTextField;
    private javax.swing.JButton HScanButton1;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextArea MainTextWin;
    private javax.swing.JButton QuitButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JButton StopButton;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JButton VScanButton;
    private javax.swing.ButtonGroup directionsGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup revsGroup;
    private javax.swing.ButtonGroup stepsGroup;
    // End of variables declaration//GEN-END:variables
}
